name: Main

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go 1.23.2
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.2

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v -o ./tmp/main.exe ./cmd/workbenefitsapi

      - name: Run go vet
        run: go vet ./...

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0

      - name: Run golangci-lint
        run: golangci-lint run

      # - name: Run tests
      #   run: go test -race -vet=off ./...
